name: Doxygen deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt install doxygen graphviz -y

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          mv docs/* .
          rm -rf docs
          touch .nojekyll  # Prevents GitHub Pages from ignoring underscores
          git add .
          git commit -m "Deploy Doxygen docs"
          git push --force origin gh-pages
