name: Generate Doxygen Docs

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt install doxygen graphviz -y

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Commit and Push Docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs
          git commit -m "Update Doxygen documentation" || echo "No changes to commit"
          git push
